### ISSUE TITLE
How to obfuscate watch target?

### ISSUE THREAD

**Issue by euroboy** [preemptive/PPiOS-Rename#10]
I'm trying to obfuscate the main app and watch executables, but after that symbols.h file contains the following:

```
#ifndef DOUBLE_OBFUSCATION_GUARD_PPIOS
#define DOUBLE_OBFUSCATION_GUARD_PPIOS
#else
#error Double obfuscation detected. This will result in an unobfuscated binary. Please see the documentation for details.
#endif
```

Is there a way to also obfuscate the watch target, or it is not yet supported?

**Comment by neuralmer** [comment]
*PPiOS-Rename* does not currently support watchOS.  This means that we do not test on the platform, but it does not necessarily mean that it does not work on watchOS.

*PPiOS-Rename* when it obfuscates the sources alters `*-Prefix.pch` files, each time adding a `#include` line for `symbols.h`.  Order of the steps to apply renaming (build, analyze, obfuscate, build again) is critical for *PPiOS-Rename* to work correctly.  If sources are "obfuscated twice", the `.pch` file can get two include lines for `symbols.h`, and this can indicate that something was done incorrectly (and the resulting build would otherwise not work or remain unobfuscated).  The check you include in your question is responsible for verifying this -- specifically that in any single translation unit there is only one copy of `symbols.h` included.

If you are seeing the double obfuscation error emitted by the build (because of this check), then either some steps have been done out of order, or `symbols.h` has otherwise been included more than once.
