### ISSUE TITLE
Problem with PPIOS-Rename

### ISSUE THREAD

**Issue by VladPodvoiskyi** [preemptive/PPiOS-Rename#12]
I use the PPIOS-Rename framework. I'm doing everything right on the description, but why does not it obfuscate my methods and classes? What could be the reason?

**Comment by cHaLkdusT** [comment]
Hi @VladPodvoiskyi , are you working on a dynamic framework?

**Comment by VladPodvoiskyi** [comment]
What is the difference between dynamic and static frameworks? When I use PPIOS-Rename, the result is the same effect for new projects that are already being developed. The file symbols.h is defaulted by the same information. And in the project itself - no method or function is obfuscated

**Comment by cHaLkdusT** [comment]
Dynamic frameworks are those with extension type of **.framework** whilst static frameworks are those with **.a** extension type. Have you analyze first your framework?

**Comment by VladPodvoiskyi** [comment]
Thank you! 
No, we did not separately analyze anything, but immediately the whole project. In the description it is written that he himself must walk through the project and all frameworks.

**Comment by neuralmer** [comment]
Sorry for the delayed response.

In order to help you with this issue, I will need additional information:
1. Are you not seeing any renaming happening, or just not as much as you would expect?
2. Are you applying *PPiOS-Rename* to an app, a static library (`.a`), or a dynamic framework (`.framework`)?
3. Are you working with more than one project in your workspace?

Please take a look at the `symbols.map` file.  It will contain the renamings that will be applied to your project.  If it does not contain renamings that you expect, there may be an issue with analysis.  If it does contain the right renamings, then there is probably an issue applying the renamings through the `*-Prefix.pch` files.  See details under [this troubleshooting topic](https://github.com/preemptive/PPiOS-Rename#missing-pch-file) (even though you are not receiving this error).  It is also possible that you have a `*-Prefix.pch` file that is being modified to include `symbols.h`, but that file is not being used by your project.

Also it is important to know that not all methods or all components of a selector can be renamed in Objective-C, since method resolution happens at run-time.  Additionally, because of the way that *PPiOS-Rename* works, a name used by system libraries cannot be renamed even when used in other contexts.

**Comment by neuralmer** [comment]
Please re-open and provide additional detail if this problem persists.
