### ISSUE TITLE
[Crash] Value for undefined key

### ISSUE THREAD

**Issue by andreiChis70** [preemptive/PPiOS-Rename#13]
Hello,
I did obfuscate my project using the correct steps and everything worked till I found this crash.
**ppios-rename version: v1.2.0**

2018-04-18 11:43:15.905099+0300 XXXX[1907:388059] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<k5kGGmHJ 0x17ad4fc0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key XXXX.'

I believe my class does not recognize my property after obfuscation.
How should I fix this crash ?

Thank you!

**Comment by neuralmer** [comment]
*PPiOS-Rename* can interfere with key-value coding compliance, and interaction with properties needs to use `NSStringFromSelector(@selector(keyPath))` as discussed [here](https://github.com/preemptive/PPiOS-Rename#key-value-observing-kvo).  The class corresponding to `k5kGGmHJ` could be excluded from renaming with `-F '!classname'`, but this should not be necessary.

It is also important to test all of the features of your application after obfuscation, since renaming can affect name-method resolution which only happens at run-time.

If this does not address your problem, please reopen this issue.
