### ISSUE TITLE
Error Analyzing App: Cannot find offset for address ... in stringAtAddress

### ISSUE THREAD

**Issue by carusd** [preemptive/PPiOS-Rename#18]
happens in the analyze phaze, terminal log this:

ppios-rename[14271:115927] Error: Cannot find offset for address 0x700000000100a617 in stringAtAddress:

**Comment by Muhammedayaz77** [comment]
FOR ME ALSO

**Comment by neuralmer** [comment]
I have tested [our sample app](https://github.com/preemptive/PPiOS-Sample-Vie) in Xcode version 9.4 (9F1027a) with *PPiOS-Rename* v1.2.0 on macOS High Sierra 10.13.6 (17G65) without issue.  So this issue does not appear to be simply caused by running PPiOS-Rename with Xcode 9.4 in High Sierra.

In particular, this error suggests that there is some unexpected condition in code in app being analyzed by *PPiOS-Rename*. Can either of you (@carusd or @Muhammedayaz77) provide additional detail about what exactly you're doing that caused this issue?

1. Are you using only Objective-C code? (Swift is **not** supported.)
2. What version of *PPiOS-Rename* are you using?
3. What is the target version of iOS for your build?
4. What is the detailed version number of Xcode if different from what I listed (find this info in Xcode > About Xcode)?
5. Are there unusual libraries that you are using?
6. What is the target being analyzed, is it compiled for simulator or a device (e.g. x86 or arm)?
7. Have you tried processing this app with other versions of Xcode or other versions of *PPiOS-Rename*?

**Comment by neuralmer** [comment]
I get the error you are seeing if I try to analyze the binary from a Swift app:
```
~/Downloads/PPiOS-Rename-v1.2.0/ppios-rename --analyze .../swift-2048.app/swift-2048
2018-07-11 14:58:29.573 ppios-rename[4380:68241] Error: Cannot find offset for address 0xa800000001000270 in stringAtAddress:
```
Swift is not supported.

Please reopen with additional details if you are seeing this issue with an Objective-C app.
