### ISSUE TITLE
Confuse the class, but the xib name is still not confused before the class name and xib name is inconsistent, resulting in Viewcontroller load can not find Viewcontroller.xib, how to solve this problem?

### ISSUE THREAD

**Issue by jtans** [preemptive/PPiOS-Rename#3]
Confuse the class, but the xib name is still not confused before the class name and xib name is inconsistent, resulting in Viewcontroller load can not find Viewcontroller.xib, how to solve this problem?

**Comment by truist** [comment]
Is the xib something you made, or part of an external library? From the readme:

> If you're using external libraries which provide Interface Builder files, be sure to ignore those symbols as they won't work when you launch the app and try to use them. You can do that using the -F option to the Analyze phase.

**Comment by neuralmer** [comment]
There are two possible solutions:
1. Exclude your UIViewController subclasses from renaming (using `-x MyViewController` to exclude class name, but not its members).  This will allow the implicit association between view controller class name and `.xib` filename to work as it does without renaming.
2. Or, explicitly specify the `.xib` to use:
```
// instead of:
_myController = [[MyViewController alloc] init];
// replace with:
_myController = [[MyViewController alloc] initWithNibName:@"MyViewController" bundle:nil];
```
This string literal specifies the `.xib` to use by name ("xib" becomes a "nib" once it is compiled), and since PPiOS-Rename doesn't alter string, the name will remain unmodified.

We will be releasing a sample project that actually demonstrates this exact case, if I understand your question correctly.

**Comment by neuralmer** [comment]
Please see the newly released sample project: https://github.com/preemptive/PPiOS-Sample-Vie

Specifically related is the section about PPiOS-Rename configuration: https://github.com/preemptive/PPiOS-Sample-Vie#ppios-rename-configuration

I believe this addresses your issue and will close this issue.  Please feel free to comment on this issue again if this does not address your issue.

**Comment by jtans** [comment]
Thank you for your answer, according to the steps you said, my problem has been solved
