### ISSUE TITLE
iOS8 support

### ISSUE THREAD

**Issue by issiht** [preemptive/PPiOS-Rename#5]
Hi,
This is not an issue, but a question.
While I understand that you do not support lower than iOS9, I'm curious as to whether you know of any incompatibilities with iOS8. Are the expected related incompatibilities related to XIB, storyboards etc. Or is it something else?

**Comment by neuralmer** [comment]
I know of no expected incompatibilities.  I would expect PPiOS-Rename to work for Objective-C apps targeting iOS 8, and I have tested PPiOS-Rename on apps using iOS 8.  That said, we are unlikely to direct development effort to fix an issue specific to iOS 8 since we are not claiming support of that OS.
