### ISSUE TITLE
Double Obfuscation Issue

### ISSUE THREAD

**Issue by santosh4nsec** [preemptive/PPiOS-Rename#7]
Have used PPiOS-Rename for my project and observed double obfuscation detected. To fix this issue, the documentation says that make sure that source tree is always reset to an unmodified state. Could you please explain in detail, what is that need to be taken care here.

**Comment by neuralmer** [comment]
As part of the obfuscation process, *PPiOS-Rename* alters some source files and resources in a way that it cannot reverse on its own. The expectation is that source/version control will be used to undo those changes. In order to avoid tying the instructions to a particular tool, this aspect of the instructions are somewhat vague.

The "unmodified state" means the state of the sources prior to changes that *PPiOS-Rename* makes. So ... after configuring *PPiOS-Rename* but before running it.

What this actually means from the point of view of setting up a new project is that you need to do *all* the steps of setup and commit those changes _before_ testing them. This is what is meant in step 19 of [Project Setup](https://github.com/preemptive/PPiOS-Rename#project-setup).

Testing the new targets actually changes the sources, and those changes need to be reverted before trying to fix any issues with the *PPiOS-Rename* configuration.
